### ISSUE TITLE
Problem in staging with template loading

### ISSUE THREAD

**Issue by ppazos** [ppazos/open-ehr-gen-framework#151]
DemographicService - PA LOCAL
======= +++++++++ =======
======= Bootstrap =======
======= +++++++++ =======
- Cambio de TimeZone a la de Montevideo/Buenos Aires
- Carga arquetipos en memoria
loadAllRecursive: archetypes/ehr/
loadAllRecursive: archetypes/ehr/cluster
loadAllRecursive: archetypes/ehr/composition
loadAllRecursive: archetypes/ehr/element
loadAllRecursive: archetypes/ehr/entry
loadAllRecursive: archetypes/ehr/entry/action
loadAllRecursive: archetypes/ehr/entry/admin_entry
loadAllRecursive: archetypes/ehr/entry/evaluation
loadAllRecursive: archetypes/ehr/entry/instruction
loadAllRecursive: archetypes/ehr/entry/observation
loadAllRecursive: archetypes/ehr/section
loadAllRecursive: archetypes/ehr/structure
- Carga templates en memoria
[Fatal Error] :7:13: The markup in the document following the root element must be well-formed.
2015-08-15 02:56:17,525 ERROR  ContextLoader - Context initialization failed
org.springframework.beans.factory.access.BootstrapException: Error executing bootstraps; nested exception is org.codehaus.groovy.runtime.InvokerI
nvocationException: org.xml.sax.SAXParseException; lineNumber: 7; columnNumber: 13; The markup in the document following the root element must be
 well-formed.
        at org.codehaus.groovy.grails.web.context.GrailsContextLoader.createWebApplicationContext(GrailsContextLoader.java:90)
        at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:215)
        at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:47)
        at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4973)
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5467)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:901)
        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:877)
        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:632)
        at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:1083)
        at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1880)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.codehaus.groovy.runtime.InvokerInvocationException: org.xml.sax.SAXParseException; lineNumber: 7; columnNumber: 13; The markup in
the document following the root element must be well-formed.
        at grails.util.Environment.evaluateEnvironmentSpecificBlock(Environment.java:265)
        at grails.util.Environment.executeForEnvironment(Environment.java:258)
        at grails.util.Environment.executeForCurrentEnvironment(Environment.java:234)
        ... 5 more
Caused by: org.xml.sax.SAXParseException; lineNumber: 7; columnNumber: 13; The markup in the document following the root element must be well-for
med.
        at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1239)
        at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:648)
        at templates.TemplateManager.parseTemplate(TemplateManager.groovy:43)
        at templates.TemplateManager.this$2$parseTemplate(TemplateManager.groovy)
        at templates.TemplateManager$_loadAllRecursive_closure7.doCall(TemplateManager.groovy:397)
        at templates.TemplateManager.loadAllRecursive(TemplateManager.groovy:385)
        at templates.TemplateManager.this$2$loadAllRecursive(TemplateManager.groovy)
        at templates.TemplateManager$_loadAllRecursive_closure8.doCall(TemplateManager.groovy:412)
        at templates.TemplateManager.loadAllRecursive(TemplateManager.groovy:411)
        at templates.TemplateManager.this$2$loadAllRecursive(TemplateManager.groovy)
        at templates.TemplateManager$_loadAllRecursive_closure8.doCall(TemplateManager.groovy:412)
        at templates.TemplateManager.loadAllRecursive(TemplateManager.groovy:411)
        at templates.TemplateManager.this$2$loadAllRecursive(TemplateManager.groovy)
        at templates.TemplateManager$this$2$loadAllRecursive.callCurrent(Unknown Source)
        at templates.TemplateManager.loadAll(TemplateManager.groovy:370)
        at templates.TemplateManager$loadAll.call(Unknown Source)
        at BootStrap$_closure1.doCall(BootStrap.groovy:120)
        ... 8 more
Aug 15, 2015 3:56:17 AM org.apache.catalina.core.StandardContext startInternal
SEVERE: Error listenerStart
Aug 15, 2015 3:56:17 AM org.apache.catalina.core.StandardContext startInternal
SEVERE: Context [/ehrgen-1.4-0.8b3] startup failed due to previous errors
Aug 15, 2015 3:56:19 AM org.apache.catalina.loader.WebappClassLoader clearReferencesJdbc
SEVERE: The web application [/ehrgen-1.4-0.8b3] registered the JDBC driver [com.mysql.jdbc.Driver] but failed to unregister it when the web appli
cation was stopped. To prevent a memory leak, the JDBC Driver has been forcibly unregistered.
Aug 15, 2015 3:56:19 AM org.apache.catalina.loader.WebappClassLoader clearReferencesThreads
SEVERE: The web application [/ehrgen-1.4-0.8b3] appears to have started a thread named [Abandoned connection cleanup thread] but has failed to st
op it. This is very likely to create a memory leak.
Aug 15, 2015 3:56:19 AM org.apache.catalina.loader.WebappClassLoader clearReferencesThreads
SEVERE: The web application [/ehrgen-1.4-0.8b3] appears to have started a thread named [net.sf.ehcache.CacheManager@130f74e] but has failed to st
op it. This is very likely to create a memory leak.
Aug 15, 2015 3:56:19 AM org.apache.catalina.loader.WebappClassLoader clearReferencesThreads
SEVERE: The web application [/ehrgen-1.4-0.8b3] appears to have started a thread named [org.hibernate.cache.UpdateTimestampsCache.data] but has f
ailed to stop it. This is very likely to create a memory leak.
Aug 15, 2015 3:56:19 AM org.apache.catalina.loader.WebappClassLoader clearReferencesThreads
SEVERE: The web application [/ehrgen-1.4-0.8b3] appears to have started a thread named [org.hibernate.cache.StandardQueryCache.data] but has fail
ed to stop it. This is very likely to create a memory leak.
Aug 15, 2015 3:56:19 AM org.apache.catalina.loader.WebappClassLoader checkThreadLocalMapForLeaks
SEVERE: The web application [/ehrgen-1.4-0.8b3] created a ThreadLocal with key of type [org.codehaus.groovy.grails.orm.hibernate.support.Hibernat
ePersistenceContextInterceptor$1] (value [org.codehaus.groovy.grails.orm.hibernate.support.HibernatePersistenceContextInterceptor$1@b8ca32]) and
a value of type [java.lang.Boolean] (value [false]) but failed to remove it when the web application was stopped. Threads are going to be renewed
 over time to try and avoid a probable memory leak.
Aug 15, 2015 3:56:19 AM org.apache.catalina.loader.WebappClassLoader checkThreadLocalMapForLeaks
SEVERE: The web application [/ehrgen-1.4-0.8b3] created a ThreadLocal with key of type [org.codehaus.groovy.grails.orm.hibernate.support.Hibernat
ePersistenceContextInterceptor$2] (value [org.codehaus.groovy.grails.orm.hibernate.support.HibernatePersistenceContextInterceptor$2@1e2b3a8]) and
 a value of type [java.lang.Integer] (value [0]) but failed to remove it when the web application was stopped. Threads are going to be renewed ov
er time to try and avoid a probable memory leak.
Aug 15, 2015 3:56:20 AM org.apache.catalina.startup.HostConfig deployWAR
INFO: Deployment of web application archive /var/lib/openshift/55b46554e0b8cde13100004b/app-root/runtime/dependencies/jbossews/webapps/ehrgen-1.4
-0.8b3.war has finished in 230,671 ms
Aug 15, 2015 3:56:20 AM org.apache.coyote.AbstractProtocol start
INFO: Starting ProtocolHandler ["http-bio-127.2.128.1-8080"]
Aug 15, 2015 3:56:20 AM org.apache.catalina.startup.Catalina start
INFO: Server startup in 237484 ms
Aug 15, 2015 3:56:40 AM org.apache.catalina.loader.WebappClassLoader loadClass
INFO: Illegal access: this web application instance has been stopped already.  Could not load net.sf.ehcache.store.compound.CompoundStore$KeySet.
  The eventual following stack trace is caused by an error thrown for debugging purposes as well as to attempt to terminate the thread which caus
ed the illegal access, and has no functional impact.
java.lang.IllegalStateException
        at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1612)
        at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1571)
        at net.sf.ehcache.store.compound.CompoundStore.keySet(CompoundStore.java:207)
        at net.sf.ehcache.store.compound.factories.DiskStorageFactory$DiskExpiryTask.run(DiskStorageFactory.java:661)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)

Templates:

[ehrgen-ehrserver.rhcloud.com templates]\> ls -R .
.:
composition  entry  section

./composition:

./entry:
action  admin_entry  evaluation  instruction  observation

./entry/action:
EHRGen-EHR-adm_sust.v1.xml  EHRGen-EHR-cumplimiento de ordenes.v1.xml

./entry/admin_entry:
EHRGen-EHR-same_uy_ubicacion.v1.xml

./entry/evaluation:
EHRGen-EHR-problemas.v1.xml  EHRGen-EHR-triage.v1.xml
EHRGen-EHR-resumen.v1.xml

./entry/instruction:
EHRGen-EHR-movimiento_paciente.v1.xml  EHRGen-EHR-pedido_laboratorio.v1.xml
EHRGen-EHR-pedido_imagenes.v1.xml      EHRGen-EHR-test_ordenes.v1.xml

./entry/observation:
EHRGen-EHR-blood_pressure_liotta.v1.xml
EHRGen-EHR-blood_pressure.v1.xml
EHRGen-EHR-blood_pressure.v2.xml
EHRGen-EHR-blood_pressure.v3.xml
EHRGen-EHR-cluster_obligatorio_multiple_struct.v1.xml
EHRGen-EHR-cluster_obligatorio_multiple.v1.xml
EHRGen-EHR-cluster_obligatorio.v1.xml
EHRGen-EHR-cluster_obligatorio.v2.xml
EHRGen-EHR-cluster_oblig_multiple_element_oblig.v1.xml
EHRGen-EHR-consulta_evolucion.v1.xml
EHRGen-EHR-diagnosticos.v1.xml
EHRGen-EHR-fallecimiento.v1.xml
EHRGen-EHR-pressao.v1.xml <<<<< this is the problem
EHRGen-EHR-registroxxxx.v1.xml
EHRGen-EHR-resumen_clinico.v1.xml
EHRGen-EHR-test_body_weight.v1.xml
EHRGen-EHR-Teste.v1.xml  <<<<< this is the problem
EHRGen-EHR-test_sts.v1.xml

./section:
EHRGen-EHR-columna_vertebral.v1.xml
EHRGen-EHR-contexto_del_evento.v1.xml
EHRGen-EHR-demo.v1.xml
EHRGen-EHR-derivacion.v1.xml
EHRGen-EHR-disfuncion_neurologica.v1.xml
EHRGen-EHR-estado_circulatorio.v1.xml
EHRGen-EHR-evaluacion_columna_vertebral.xml
EHRGen-EHR-examinacion_fisica.v1.xml
EHRGen-EHR-exposicion_corporal_total.v1.xml
EHRGen-EHR-prehospitalario.v1.xml
EHRGen-EHR-same_uy.v1.xml
EHRGen-EHR-test_dates.v1.xml
EHRGen-EHR-ventilacion.v1.xml
EHRGen-EHR-via_aerea.v1.xml
[ehrgen-ehrserver.rhcloud.com templates]\>

[ehrgen-ehrserver.rhcloud.com observation]\> cat EHRGen-EHR-Teste.v1.xml

```xml
<template>
  <id>EHRGen-EHR-Teste.v1</id>
  <name>Pressão</name>
  <root_archetype>
    <archetype type='observation' id='openEHR-EHR-OBSERVATION.blood_pressure.v3'                                                                                                                                 pageZone='content' includeAll='true' />
  </root_archetype>
</template><template>
  <id>EHRGen-EHR-Teste.v1</id>
  <name>Pressão</name>
  <root_archetype>
    <archetype type='observation' id='openEHR-EHR-OBSERVATION.blood_pressure.v3'                                                                                                                                 pageZone='content' includeAll='true' />
  </root_archetype>
```

Template upload seems to be appending not replacing.

**Comment by ppazos** [comment]
The problem is domain/createTemplate doesnt chekc if there is another template already with the same name.

**Comment by ppazos** [comment]
Check added to verify if the template already exists.
